import type {FinalResponse, Economics} from '../lib/final-types.ts';
import {displayMeasurement,deadlineLabel,readable} from '../lib/final-response.ts';
const percent=(v:string)=>`${(Number(v)*100).toFixed(1)}%`;
const ECONOMIC_LABELS:Record<keyof Economics,string>={gross_income_usd:'Gross Return',lifecycle_cost_usd:'Lifecycle Cost',fixed_cost_usd:'Fixed Cost (included in lifecycle)',quote_execution_cost_usd:'Quote/Execution Loss',expected_net_profit_usd:'Expected Net Profit',expected_net_return:'Expected Net Return',net_apy:'Net APY'};
function EconomicsView({value}:{value:Economics}) {return <dl className="detailGrid">{Object.entries(ECONOMIC_LABELS).map(([k,label])=><div key={k}><dt>{label}</dt><dd>{displayMeasurement(value[k as keyof Economics])}</dd></div>)}</dl>;}
export function DecisionView({data}:{data:FinalResponse}) {
 const rec=data.recommendation;
 const legacy=data.comparison.legacy_linear;
 return <>
  <article className="panel notice" role="status"><h2>{data.evidence.mode==='SYNTHETIC_EVALUATION_ONLY'?'Synthetic Evaluation Only':'Production Evidence: Unresolved'}</h2><p>{data.evidence.mode==='SYNTHETIC_EVALUATION_ONLY'?'Uses modelled evaluation assumptions. Not live market evidence or execution readiness.':'Required runtime, admission and economics evidence is unresolved. Positive allocation fails closed.'}</p></article>
  <article className="panel"><div className="sectionLabel">Policy-Aware Amount Optimizer</div><h2>{rec.state==='KEEP_IDLE'?'Keep 100% Idle':rec.state==='SELECTED_REVALIDATION_FAILED'?'Keep Idle — Revalidation Failed':'Decision-sleeve recommendation'}</h2><p>{data.input.decision_amount_0g} 0G decision amount · {data.input.profile} · Revalidation: {readable(rec.revalidation_state)}</p>
   <div className="allocationBar" aria-label="Current request allocation">{data.strategies.map((s,i)=><div key={s.strategy_id} style={{width:percent(s.allocated_weight),background:['#97cbff','#c9ff4a','#cba7ff','#ffbb82','#ff8080'][i]}} title={s.display_name}/>)}<div style={{width:percent(rec.idle_weight),background:'#6b7280'}} title="Idle"/></div>
   <div className="allocationList">{data.strategies.map(s=><div className="allocationRow" key={s.strategy_id}><strong>{s.display_name} {s.allocation_gate==='CLOSED'&&<span className="status">CLOSED</span>}</strong><span>{percent(s.allocated_weight)} · {s.allocated_amount_0g} 0G</span></div>)}<div className="allocationRow"><strong>Idle</strong><span>{percent(rec.idle_weight)} · {rec.idle_amount_0g} 0G</span></div></div>
  </article>
  <article className="panel"><h2>Expected Economics</h2><EconomicsView value={rec.economics}/><p className="muted">Fixed cost is a component of lifecycle cost, charged once. Quote loss is separate. Unassessed evidence is not zero.</p></article>
  <article className="panel"><h2>Risk &amp; Policy</h2><div className="constraintGrid">{([['concentration','Concentration'],['staking_stress','Staking Stress'],['lp_absolute_stress','LP Absolute Stress']] as const).map(([key,label])=>{const c=data.risk[key];return <div className="constraintChip" key={key}><span>{label}</span><strong>{c.value===null?'Not assessed':percent(c.value)} / {percent(c.limit)}</strong><small>{readable(c.state)}</small></div>;})}</div><p>Total decision-sleeve stress: {displayMeasurement(data.risk.total_decision_sleeve_stress)}</p><p className="muted">{data.risk.qualification}. Deterministic modelled stress limits; not event probabilities or VaR.</p><p>Binding Constraints: {data.policy.binding_constraints.length?data.policy.binding_constraints.map(readable).join(', '):'None selected'}</p><p>Required unresolved constraints: {data.policy.unresolved_required_constraints.length?data.policy.unresolved_required_constraints.join(', '):'None in selected assessment'}</p><p>Policy assessment: {readable(data.policy.state)}</p></article>
  <article className="panel"><h2>Liquidity &amp; Exit Timing</h2><p>Holding horizon: {data.liquidity.holding_horizon_days} days</p><p>Cash deadline: {data.liquidity.cash_deadline_days===null?'Not requested':`${data.liquidity.cash_deadline_days} days from exit decision`}</p><p>{deadlineLabel(data.liquidity.deadline_state)} · Idle time-to-cash: 0 days</p>{data.strategies.filter(s=>Number(s.allocated_weight)>0).map(s=><p key={s.strategy_id}>{s.display_name}: modelled time-to-cash {displayMeasurement(s.liquidity.time_to_cash_days)} · {deadlineLabel(s.liquidity.deadline_state)}</p>)}<p className="muted">Holding horizon and time-to-cash are separate. Modelled timing is not a withdrawal guarantee; synchronous operations still require qualified quotes and admission.</p></article>
  <article className="panel"><h2>Five Strategy Diagnostics</h2>{data.strategies.map(s=><details className="strategyEntry" key={s.strategy_id}><summary><strong>{s.display_name}</strong> · {s.allocation_gate==='CLOSED'?'CLOSED':readable(s.allocation_result)} · {percent(s.allocated_weight)} / {s.allocated_amount_0g} 0G</summary><div className="strategyDetails"><p>Canonical state: {readable(s.canonical_state)} · Allocation gate: {s.allocation_gate} · Structural candidate: {s.structural_candidate?'Yes':'No'} · Integration: {readable(s.integration_state)}</p><p>Admission: {readable(s.technical_admission)} · Economics: {readable(s.economics_state)} · Policy feasibility: {readable(s.policy_feasibility)}</p><p>{s.economics_basis==='SELECTED_EXACT_AMOUNT'?'Selected exact amount':'Unselected candidate diagnostic'}: {s.diagnostic_amount_0g} 0G. These diagnostics do not represent income on a zero allocation.</p><EconomicsView value={s.economics}/><p>Deterministic strategy stress: {displayMeasurement(s.risk.loss_fraction)} · Absolute stressed loss: {displayMeasurement(s.risk.absolute_loss_usd)} · {readable(s.risk.state)} (same diagnostic amount)</p><p>Modelled time-to-cash: {displayMeasurement(s.liquidity.time_to_cash_days)} · {deadlineLabel(s.liquidity.deadline_state)}</p><p>Binding constraints (diagnostic candidate): {s.binding_constraints.map(readable).join(', ')||'None'}</p><ul className="diagnosticReasons">{s.rejection_reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><p>Protocol availability (canonical metadata): {s.protocol_availability} — external protocol only, not capstone execution proof · Runtime configuration: Unresolved</p><p>Execution readiness: Not established · Public proof: Not established</p><details><summary>Evidence provenance</summary><pre className="provenance">{JSON.stringify(s.evidence,null,2)}</pre></details></div></details>)}</article>
  <article className="panel"><h2>Status &amp; Readiness</h2><dl className="detailGrid">{Object.entries({Scope:data.run_scope.scope,'Runtime configuration':data.evidence.runtime_binding,Recommendation:rec.state,'Execution readiness':data.readiness.execution_readiness,'Public/live proof':data.readiness.public_proof,'Whole-portfolio compliance':data.run_scope.whole_portfolio_compliance}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>Existing positions: {data.run_scope.existing_positions}. Public deployment is not required or planned.</p></article>
  <article className="panel"><h2>Current-input Legacy Comparison</h2><p>Comparison methods support different economics/risk/deadline features; values are not always directly equivalent.</p><p>{legacy.capability_warning}</p>{legacy.state==='ASSESSED'?<><p>Legacy allocation: {data.strategies.map(s=>`${s.display_name} ${percent(legacy.allocation_weights[s.strategy_id])}`).join(' · ')} · Idle {percent(legacy.idle_weight)}</p><p>Legacy selection-objective profit: {displayMeasurement(legacy.selection_expected_net_profit)} · Comparability: LIMITED</p></>:<p>Not assessed: canonical economics and runtime evidence unresolved.</p>}</article>
 </>;
}
