'use client';
import {useState} from 'react';
import type {FormEvent} from 'react';
import type {FinalResponse,EvidenceMode} from '../lib/final-types.ts';
import type {RiskProfile} from '../lib/types.ts';
import {parseFinalResponse} from '../lib/final-response.ts';
import {DecisionView} from './decision-view';
export default function Home() {
 const [amount,setAmount]=useState('1000'),[horizon,setHorizon]=useState('90'),[deadline,setDeadline]=useState('');
 const [profile,setProfile]=useState<RiskProfile>('Balanced'),[mode,setMode]=useState<EvidenceMode>('PRODUCTION');
 const [data,setData]=useState<FinalResponse|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>) {event.preventDefault();setLoading(true);setError(null);setData(null);try {const response=await fetch('/api/decision-sleeve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision_amount_0g:Number(amount),profile,holding_horizon_days:Number(horizon),cash_deadline_days:deadline===''?null:Number(deadline),evidence_mode:mode})});const text=await response.text();if(!response.ok) {const value:unknown=JSON.parse(text);throw Error(typeof value==='object'&&value!==null&&'error' in value?String(value.error):'API request failed');}setData(parseFinalResponse(text));} catch(e) {setError(e instanceof Error?e.message:'API request failed');} finally {setLoading(false);}}
 return <main className="shell"><header className="topbar"><h1>Ascend Optimizer</h1><span>Prototype analysis interface</span></header><section className="panel scopeBanner"><h2>Scope: Decision Sleeve</h2><p>This run allocates the specified 0G decision amount only. Existing positions are not rebalanced and whole-portfolio compliance is not assessed.</p></section><div className="dashboardLayout"><form className="panel inputPanel" onSubmit={submit}><h2>Current Decision Input</h2><label>Decision Amount (0G)<input required type="number" min="0.00000001" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Profile<select value={profile} onChange={e=>setProfile(e.target.value as RiskProfile)}>{(['Conservative','Balanced','Aggressive'] as const).map(p=><option key={p}>{p}</option>)}</select></label><label>Holding Horizon (days)<input required type="number" min="0.01" step="any" value={horizon} onChange={e=>setHorizon(e.target.value)}/></label><label>Optional Cash Deadline (days)<input type="number" min="0" step="any" value={deadline} placeholder="Not requested" onChange={e=>setDeadline(e.target.value)}/></label><p className="muted">Maximum acceptable modelled delay from exit decision until native 0G is available.</p><label>Evidence Mode<select value={mode} onChange={e=>setMode(e.target.value as EvidenceMode)}><option value="PRODUCTION">Production evidence (fail closed)</option><option value="SYNTHETIC_EVALUATION_ONLY">Synthetic Evaluation Only</option></select></label><p className="muted">Synthetic mode uses modelled assumptions, not current market economics.</p><button className="primaryButton" disabled={loading}>{loading?'Assessing…':'Optimize Decision Sleeve'}</button>{error&&<div className="errorBox" role="alert">API error: {error}</div>}</form><section className="results" aria-live="polite">{data?<DecisionView data={data}/>:<article className="panel emptyState">Submit a decision amount to assess allocation. Idle is a valid outcome; execution readiness and public proof are not established.</article>}</section></div></main>;
}
