import { STRATEGY_IDS } from './final-types.ts';
import type { FinalResponse, Measurement, DeadlineState } from './final-types.ts';
function obj(x:unknown):Record<string,unknown> {if (!x || typeof x!=='object' || Array.isArray(x)) throw Error('Invalid final contract object');return x as Record<string,unknown>;}
function fixed(x:unknown, choices:readonly unknown[]) {if (!choices.includes(x)) throw Error('Invalid final contract state');}
function decimal(x:unknown) {if(typeof x!=='string'||!/^[-]?\d+(\.\d+)?$/.test(x)||!Number.isFinite(Number(x))) throw Error('Invalid final decimal');return Number(x);}
function measurement(x:unknown) {const m=obj(x);fixed(m.state,['ASSESSED','NOT_ASSESSED','MISSING','POLICY_UNDEFINED','NOT_SUPPORTED']);fixed(m.unit,['USD','FRACTION','DAYS']);if(m.state==='ASSESSED') decimal(m.value);else if(m.value!==null) throw Error('Unavailable measurement must be null');}
function economics(x:unknown) {const e=obj(x);for(const k of ['gross_income_usd','lifecycle_cost_usd','fixed_cost_usd','quote_execution_cost_usd','expected_net_profit_usd','expected_net_return','net_apy']) measurement(e[k]);}
export function parseFinalResponse(text:string):FinalResponse {
 const root=obj(JSON.parse(text));fixed(root.schema_version,['1.4']);
 const scope=obj(root.run_scope);fixed(scope.scope,['DECISION_SLEEVE']);fixed(scope.whole_portfolio_compliance,['NOT_ASSESSED']);fixed(scope.existing_positions,['EXOGENOUS_NOT_OPTIMIZED']);
 const input=obj(root.input);if(decimal(input.decision_amount_0g)<=0||decimal(input.holding_horizon_days)<=0) throw Error('Invalid capital or horizon');
 fixed(input.profile,['Conservative','Balanced','Aggressive']);fixed(input.evidence_mode,['PRODUCTION','SYNTHETIC_EVALUATION_ONLY']);if(input.cash_deadline_days!==null && decimal(input.cash_deadline_days)<0) throw Error('Invalid deadline');
 const rec=obj(root.recommendation);fixed(rec.method,['POLICY_AWARE_AMOUNT_OPTIMIZER']);fixed(rec.state,['RECOMMENDATION_GENERATED','KEEP_IDLE','SELECTED_REVALIDATION_FAILED']);fixed(rec.revalidation_state,['PASSED','FAILED','NOT_REQUIRED']);
 const weights=obj(rec.allocation_weights),amounts=obj(rec.allocated_amounts_0g);if(Object.keys(weights).length!==5||Object.keys(amounts).length!==5) throw Error('Five allocations required');
 let total=decimal(rec.idle_weight);for(const sid of STRATEGY_IDS) {const w=decimal(weights[sid]);if(w<0||w>1||decimal(amounts[sid])<0) throw Error('Invalid allocation'); total+=w;}
 if(Math.abs(total-1)>1e-12||decimal(weights.ASCEND_STAKE_A0G)!==0||decimal(rec.idle_weight)<0||decimal(rec.idle_amount_0g)<0) throw Error('Invalid sleeve or closed gate');
 if(rec.revalidation_state==='FAILED' && decimal(rec.idle_weight)!==1) throw Error('Revalidation failure must fail closed');
 economics(rec.economics);measurement(obj(root.valuation).price_usd);
 if(!Array.isArray(root.strategies)||root.strategies.length!==5) throw Error('Five strategy rows required');
 const ids=new Set();for(const v of root.strategies) {const s=obj(v);fixed(s.strategy_id,STRATEGY_IDS);ids.add(s.strategy_id);fixed(s.allocation_result,['NOT_CANDIDATE','GATED','EXCLUDED','ALLOCATED_POSITIVE','ELIGIBLE_ZERO']);fixed(s.runtime_configuration,['UNRESOLVED']);fixed(s.execution_readiness,['NOT_ESTABLISHED']);fixed(s.public_proof,['NOT_ESTABLISHED']);fixed(s.structural_candidate,[true]);fixed(s.allocation_gate,['CONDITIONAL','CLOSED']);fixed(s.technical_admission,['UNKNOWN','SUPPORTED','UNSUPPORTED','NOT_REQUIRED']);fixed(s.policy_feasibility,['PASS','FAIL','UNRESOLVED','NOT_ASSESSED']);economics(s.economics);const sr=obj(s.risk);measurement(sr.loss_fraction);measurement(sr.absolute_loss_usd);fixed(sr.state,['ASSESSED_MODELLED','ASSESSED_OBSERVED','PARTIALLY_ASSESSED','UNRESOLVED','NOT_APPLICABLE']);const l=obj(s.liquidity);measurement(l.time_to_cash_days);fixed(l.deadline_state,['NOT_REQUESTED','COMPATIBLE_MODELLED','INCOMPATIBLE_MODELLED','UNRESOLVED']);if(!Array.isArray(s.rejection_reasons)||!s.rejection_reasons.every(x=>typeof x==='string')) throw Error('Invalid reasons');if(s.strategy_id==='ASCEND_STAKE_A0G') fixed(s.allocation_gate,['CLOSED']);}
 if(ids.size!==5) throw Error('Duplicate strategy rows');
 const risk=obj(root.risk);for(const k of ['concentration','staking_stress','lp_absolute_stress']) {const c=obj(risk[k]);fixed(c.state,['PASS','FAIL','UNRESOLVED','NOT_ASSESSED']);decimal(c.limit);if(c.value!==null) decimal(c.value);}
 measurement(risk.total_decision_sleeve_stress);const readiness=obj(root.readiness);fixed(readiness.execution_readiness,['NOT_ESTABLISHED']);fixed(readiness.public_proof,['NOT_ESTABLISHED']);fixed(readiness.public_deployment,['NOT_REQUIRED_NOT_PLANNED']);fixed(obj(root.evidence).mode,[input.evidence_mode]);
 fixed(obj(root.liquidity).deadline_state,['NOT_REQUESTED','COMPATIBLE_MODELLED','INCOMPATIBLE_MODELLED','UNRESOLVED']);fixed(obj(root.policy).version,['EVALUATION_POLICY_V1']);fixed(obj(root.policy).state,['PASS','FAIL','UNRESOLVED','NOT_ASSESSED']);obj(root.solver);const legacy=obj(obj(root.comparison).legacy_linear);fixed(legacy.state,['ASSESSED','NOT_ASSESSED']);if(typeof legacy.capability_warning!=='string') throw Error('Missing comparison qualification');if(legacy.state==='ASSESSED') {const lw=obj(legacy.allocation_weights);for(const sid of STRATEGY_IDS) decimal(lw[sid]);decimal(legacy.idle_weight);measurement(legacy.selection_expected_net_profit);fixed(legacy.profit_comparability,['LIMITED']);fixed(legacy.cash_deadline,['NOT_SUPPORTED']);fixed(legacy.risk_namespace,['LEGACY_COMPATIBILITY']);}
 if(input.evidence_mode==='PRODUCTION' && decimal(rec.idle_weight)!==1) throw Error('Unresolved production evidence cannot allocate');
 return root as unknown as FinalResponse;
}
export function readable(state:string):string {return state.toLowerCase().replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());}
export function displayMeasurement(m:Measurement):string {if(m.state!=='ASSESSED') return m.state==='MISSING'?'Missing evidence':readable(m.state);const v=Number(m.value);return m.unit==='USD'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v):m.unit==='DAYS'?`${v.toLocaleString()} days (${m.basis==='MODELLED'?'modelled':'unresolved'})`:`${(v*100).toFixed(2)}%`;}
export function deadlineLabel(state:DeadlineState):string {return {'NOT_REQUESTED':'Not requested','COMPATIBLE_MODELLED':'Compatible (modelled)','INCOMPATIBLE_MODELLED':'Incompatible (modelled)','UNRESOLVED':'Unresolved'}[state];}
